#!/usr/bin/env node

/*
	Command-line utility to interact with the User model.
*/

'use strict';

var program = require('commander');
var app     = require('./app');
var db      = require('./core/database')(app);  // load the db into app object
var pkg     = require('./package.json');
var chalk   = require('chalk');

program
	.version(pkg.version)

program
	.command('sync')
	.description('sync database')
	.action(function() {
		console.log(chalk.blue('Syncing database...'))
		app
			.sequelize
			.sync()
			.complete(function(err) {
				if (err) {
					return console.log(chalk.red('Database sync failed with ' + err));
				}
				console.log(chalk.blue('Database synced with no errors.'))
			});
	});


program.parse(process.argv);

