#!/usr/bin/env node

/*
	Command-line utility to interact with the User model.
*/

'use strict';

var program = require('commander');
var app     = require('./app');
var db      = require('./core/database')(app);
var pkg     = require('./package.json');

program
	.version(pkg.version)

program
	.command('sync')
	.description('sync database')
	.action(function() {
		//require('./server/models')
			//.sequelize
			//.sync()
			//.complete(function(err) {
				//if (err) {
					//throw err[0];
				//}
			//});
		console.log('sync me bitch');
	});


program.parse(process.argv);

